import { College, Department, Mentor, Student, CounselingNote, UserProfile } from '../types/dashboard';

export const mockColleges: College[] = [
  {
    id: 'col-1',
    code: 'FXEC',
    name: 'Francis Xavier Engineering College (Autonomous)',
    region: 'Tirunelveli, Tamil Nadu',
    status: 'Active',
    departmentsCount: 8,
    studentsCount: 2850,
    mentorsCount: 142,
    hodName: 'Dr. V. Velmurugan',
    naacGrade: 'A+',
    establishedYear: 2000,
  },
  {
    id: 'col-2',
    code: 'FXIT',
    name: 'FX College of Technology & Management',
    region: 'Vannarpettai, Tirunelveli',
    status: 'Active',
    departmentsCount: 6,
    studentsCount: 1920,
    mentorsCount: 98,
    hodName: 'Dr. G. Rajakumar',
    naacGrade: 'A',
    establishedYear: 2008,
  },
];

export const mockDepartments: Department[] = [
  {
    id: 'dept-cse',
    code: 'CSE',
    name: 'Computer Science & Engineering',
    hodName: 'Dr. E. Manohar',
    hodEmail: 'hod.cse@francisxavier.ac.in',
    hodPhone: '+91 94431 82910',
    studentsCount: 480,
    mentorsCount: 24,
    avgCgpa: 8.24,
    placementPercentage: 92.5,
    pendingArrearsCount: 18,
    iconName: 'ComputerDesktopIcon',
  },
  {
    id: 'dept-it',
    code: 'IT',
    name: 'Information Technology',
    hodName: 'Dr. A. Anand',
    hodEmail: 'hod.it@francisxavier.ac.in',
    hodPhone: '+91 94431 82911',
    studentsCount: 420,
    mentorsCount: 21,
    avgCgpa: 8.15,
    placementPercentage: 89.2,
    pendingArrearsCount: 22,
    iconName: 'CodeBracketIcon',
  },
  {
    id: 'dept-aids',
    code: 'AI&DS',
    name: 'Artificial Intelligence & Data Science',
    hodName: 'Dr. R. Anitha',
    hodEmail: 'hod.aids@francisxavier.ac.in',
    hodPhone: '+91 94431 82912',
    studentsCount: 360,
    mentorsCount: 18,
    avgCgpa: 8.38,
    placementPercentage: 94.0,
    pendingArrearsCount: 12,
    iconName: 'CpuChipIcon',
  },
  {
    id: 'dept-ece',
    code: 'ECE',
    name: 'Electronics & Communication Engg',
    hodName: 'Dr. P. Ramanathan',
    hodEmail: 'hod.ece@francisxavier.ac.in',
    hodPhone: '+91 94431 82913',
    studentsCount: 450,
    mentorsCount: 22,
    avgCgpa: 7.95,
    placementPercentage: 85.0,
    pendingArrearsCount: 34,
    iconName: 'SignalIcon',
  },
  {
    id: 'dept-eee',
    code: 'EEE',
    name: 'Electrical & Electronics Engg',
    hodName: 'Prof. A. Priya',
    hodEmail: 'hod.eee@francisxavier.ac.in',
    hodPhone: '+91 94431 82914',
    studentsCount: 320,
    mentorsCount: 16,
    avgCgpa: 7.82,
    placementPercentage: 81.5,
    pendingArrearsCount: 29,
    iconName: 'BoltIcon',
  },
  {
    id: 'dept-mech',
    code: 'MECH',
    name: 'Mechanical Engineering',
    hodName: 'Dr. S. Suresh',
    hodEmail: 'hod.mech@francisxavier.ac.in',
    hodPhone: '+91 94431 82915',
    studentsCount: 400,
    mentorsCount: 20,
    avgCgpa: 7.65,
    placementPercentage: 78.0,
    pendingArrearsCount: 45,
    iconName: 'WrenchScrewdriverIcon',
  },
  {
    id: 'dept-civil',
    code: 'CIVIL',
    name: 'Civil Engineering',
    hodName: 'Dr. V. Sundaram',
    hodEmail: 'hod.civil@francisxavier.ac.in',
    hodPhone: '+91 94431 82916',
    studentsCount: 240,
    mentorsCount: 12,
    avgCgpa: 7.55,
    placementPercentage: 74.5,
    pendingArrearsCount: 38,
    iconName: 'BuildingOfficeIcon',
  },
  {
    id: 'dept-mba',
    code: 'MBA',
    name: 'Master of Business Administration',
    hodName: 'Dr. M. Kavitha',
    hodEmail: 'hod.mba@francisxavier.ac.in',
    hodPhone: '+91 94431 82917',
    studentsCount: 180,
    mentorsCount: 9,
    avgCgpa: 8.10,
    placementPercentage: 88.0,
    pendingArrearsCount: 10,
    iconName: 'BriefcaseIcon',
  },
];

export const mockMentors: Mentor[] = [
  {
    id: 'men-101',
    name: 'Dr. K. Arulraj',
    title: 'Senior Associate Professor',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    email: 'arulraj.k@francisxavier.ac.in',
    phone: '+91 98421 11204',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    assignedStudentCount: 24,
    avgCgpa: 8.28,
    successRate: 95.8,
    officeHours: 'Mon - Fri | 03:30 PM - 05:00 PM',
    roomNo: 'CS-Block 304',
  },
  {
    id: 'men-102',
    name: 'Prof. M. Lakshmi',
    title: 'Assistant Professor (Sel. Gr.)',
    departmentId: 'dept-it',
    departmentName: 'Information Technology',
    email: 'lakshmi.m@francisxavier.ac.in',
    phone: '+91 98421 22315',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    assignedStudentCount: 20,
    avgCgpa: 8.12,
    successRate: 92.0,
    officeHours: 'Tue - Thu | 02:00 PM - 04:00 PM',
    roomNo: 'IT-Block 201',
  },
  {
    id: 'men-103',
    name: 'Dr. S. Suresh',
    title: 'Professor & Head',
    departmentId: 'dept-mech',
    departmentName: 'Mechanical Engineering',
    email: 'suresh.s@francisxavier.ac.in',
    phone: '+91 98421 33426',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    assignedStudentCount: 22,
    avgCgpa: 7.74,
    successRate: 88.5,
    officeHours: 'Mon & Wed | 11:00 AM - 01:00 PM',
    roomNo: 'ME-Block 105',
  },
  {
    id: 'men-104',
    name: 'Dr. R. Anitha',
    title: 'Associate Professor',
    departmentId: 'dept-aids',
    departmentName: 'Artificial Intelligence & Data Science',
    email: 'anitha.r@francisxavier.ac.in',
    phone: '+91 98421 44537',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    assignedStudentCount: 18,
    avgCgpa: 8.45,
    successRate: 96.2,
    officeHours: 'Daily | 04:00 PM - 05:30 PM',
    roomNo: 'AI-Block 402',
  },
];

export const mockStudents: Student[] = [
  {
    id: 'stu-1001',
    registerNo: '960721104001',
    name: 'A. Karthi Krishna',
    email: 'karthikrishna.a@student.fxec.ac.in',
    phone: '+91 91234 56789',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    collegeId: 'col-1',
    collegeName: 'Francis Xavier Engineering College (Autonomous)',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    year: 4,
    semester: 7,
    section: 'A',
    cgpa: 9.15,
    gpaHistory: [
      { semester: 1, gpa: 9.00, cgpa: 9.00 },
      { semester: 2, gpa: 9.20, cgpa: 9.10 },
      { semester: 3, gpa: 9.10, cgpa: 9.10 },
      { semester: 4, gpa: 9.25, cgpa: 9.14 },
      { semester: 5, gpa: 9.18, cgpa: 9.15 },
      { semester: 6, gpa: 9.15, cgpa: 9.15 },
    ],
    arrearsHistory: [
      {
        id: 'arr-1',
        subjectCode: 'MA3151',
        subjectName: 'Matrices and Calculus',
        semester: 1,
        status: 'passed_first_attempt',
        attemptCount: 1,
        grade: 'O',
      },
      {
        id: 'arr-2',
        subjectCode: 'CS3351',
        subjectName: 'Digital Principles & Computer Architecture',
        semester: 3,
        status: 'passed_first_attempt',
        attemptCount: 1,
        grade: 'A+',
      },
      {
        id: 'arr-3',
        subjectCode: 'CS3491',
        subjectName: 'Artificial Intelligence and Machine Learning',
        semester: 4,
        status: 'passed_first_attempt',
        attemptCount: 1,
        grade: 'O',
      },
      {
        id: 'arr-4',
        subjectCode: 'CS3591',
        subjectName: 'Computer Networks',
        semester: 5,
        status: 'passed_first_attempt',
        attemptCount: 1,
        grade: 'A+',
      },
    ],
    pendingArrearsCount: 0,
    totalHistoryArrearsCount: 0,
    attendancePercentage: 96.5,
    collegeRank: 3,
    departmentRank: 1,
    classRank: 1,
    batchRank: 1,
    percentile: 99.4,
    placementStatus: 'eligible_placed',
    companyName: 'Zoho Corporation',
    packageCtc: '8.5 LPA',
    skills: ['React.js', 'Node.js', 'Python', 'PostgreSQL', 'Docker', 'System Design'],
    certifications: [
      'AWS Certified Developer Associate',
      'NPTEL Elite + Gold in Cloud Computing',
      'Oracle Certified Java SE Professional',
    ],
    projects: [
      {
        title: 'FXEC Autonomous Mentorship & Grading Portal',
        tech: 'React, Node.js, PostgreSQL',
        description: 'Designed a real-time analytics system for tracking student academic progress and arrear histories.',
      },
      {
        title: 'AI Smart Attendance via Facial Recognition',
        tech: 'Python, OpenCV, PyTorch',
        description: 'Implemented camera-based attendance verification with 98.6% precision for campus classrooms.',
      },
    ],
    hackathons: [
      { name: 'Smart India Hackathon 2025', position: '1st Runner Up (National)', year: '2025' },
      { name: 'FXEC Innovators Expo', position: '1st Place', year: '2024' },
    ],
    internships: [
      { company: 'Zoho Tech Labs, Tenkasi', role: 'Full Stack Software Engineer Intern', duration: '6 Months (2025)' },
    ],
    interviewReadinessScore: 94,
    mentorId: 'men-101',
    mentorName: 'Dr. K. Arulraj',
    mentorRemarks: 'Exceptional academic discipline and technical leadership. Gold medallist aspirant.',
    counselingNotes: [
      {
        id: 'cn-101',
        studentId: 'stu-1001',
        studentName: 'A. Karthi Krishna',
        mentorId: 'men-101',
        mentorName: 'Dr. K. Arulraj',
        date: '2026-06-14',
        category: 'Placement',
        note: 'Discussed Zoho product engineering role technical interview rounds. Prepared system design notes.',
        actionPlan: 'Focus on database indexing and distributed caching architectures.',
        followUpDate: '2026-07-02',
      },
      {
        id: 'cn-102',
        studentId: 'stu-1001',
        studentName: 'A. Karthi Krishna',
        mentorId: 'men-101',
        mentorName: 'Dr. K. Arulraj',
        date: '2026-03-10',
        category: 'Academic',
        note: 'Reviewed Semester 6 mini-project submission. Advised publication in IEEE student conference.',
        actionPlan: 'Submit camera-ready paper by end of April.',
        followUpDate: '2026-04-15',
      },
    ],
    notifications: [
      {
        id: 'notif-1',
        studentId: 'stu-1001',
        studentName: 'A. Karthi Krishna',
        type: 'placement_ready',
        message: 'Successfully placed at Zoho Corporation with 8.5 LPA CTC package!',
        date: '2026-06-20',
        read: true,
        severity: 'success',
      },
    ],
  },
  {
    id: 'stu-1002',
    registerNo: '960721104002',
    name: 'R. Vignesh',
    email: 'vignesh.r@student.fxec.ac.in',
    phone: '+91 98765 43210',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    collegeId: 'col-1',
    collegeName: 'Francis Xavier Engineering College (Autonomous)',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    year: 4,
    semester: 7,
    section: 'A',
    cgpa: 6.85,
    gpaHistory: [
      { semester: 1, gpa: 7.20, cgpa: 7.20 },
      { semester: 2, gpa: 6.50, cgpa: 6.85 },
      { semester: 3, gpa: 6.10, cgpa: 6.60 },
      { semester: 4, gpa: 6.40, cgpa: 6.55 },
      { semester: 5, gpa: 7.10, cgpa: 6.70 },
      { semester: 6, gpa: 7.40, cgpa: 6.85 },
    ],
    arrearsHistory: [
      {
        id: 'arr-10',
        subjectCode: 'MA3354',
        subjectName: 'Discrete Mathematics',
        semester: 3,
        status: 'passed_arrear',
        attemptCount: 2,
        clearingSemester: 4,
        grade: 'B+',
      },
      {
        id: 'arr-11',
        subjectCode: 'CS3451',
        subjectName: 'Introduction to Operating Systems',
        semester: 4,
        status: 'pending',
        attemptCount: 2,
        grade: 'U',
      },
      {
        id: 'arr-12',
        subjectCode: 'CS3591',
        subjectName: 'Computer Networks',
        semester: 5,
        status: 'pending',
        attemptCount: 1,
        grade: 'U',
      },
    ],
    pendingArrearsCount: 2,
    totalHistoryArrearsCount: 3,
    attendancePercentage: 74.0,
    collegeRank: 245,
    departmentRank: 42,
    classRank: 22,
    batchRank: 42,
    percentile: 65.0,
    placementStatus: 'ineligible_arrears',
    skills: ['C++', 'Java Basics', 'HTML/CSS', 'MySQL'],
    certifications: ['NPTEL Python Programming (Passed)'],
    projects: [
      {
        title: 'Library Book Circulation System',
        tech: 'Java, MySQL',
        description: 'Desktop application for cataloging engineering library books.',
      },
    ],
    hackathons: [],
    internships: [
      { company: 'NexGen Software Solutions, Madurai', role: 'Trainee Intern', duration: '1 Month' },
    ],
    interviewReadinessScore: 58,
    mentorId: 'men-101',
    mentorName: 'Dr. K. Arulraj',
    mentorRemarks: 'Needs intensive coaching in Operating Systems & Networks backlogs before Nov end.',
    counselingNotes: [
      {
        id: 'cn-201',
        studentId: 'stu-1002',
        studentName: 'R. Vignesh',
        mentorId: 'men-101',
        mentorName: 'Dr. K. Arulraj',
        date: '2026-07-15',
        category: 'Academic',
        note: 'Warned student regarding 2 pending arrears blocking IT placement drives. Student agreed to attend special evening tutorial classes.',
        actionPlan: 'Complete 5 model question papers for OS & CN by Aug 10.',
        followUpDate: '2026-08-10',
      },
      {
        id: 'cn-202',
        studentId: 'stu-1002',
        studentName: 'R. Vignesh',
        mentorId: 'men-101',
        mentorName: 'Dr. K. Arulraj',
        date: '2026-05-04',
        category: 'Attendance',
        note: 'Attendance fell to 74%. Called parents to inform about minimum 75% university eligibility requirement.',
        actionPlan: 'Must maintain 100% attendance in upcoming 3 weeks.',
        followUpDate: '2026-05-25',
      },
    ],
    notifications: [
      {
        id: 'notif-2',
        studentId: 'stu-1002',
        studentName: 'R. Vignesh',
        type: 'multiple_arrears',
        message: '2 Pending Arrears in CS3451 & CS3591. Ineligible for campus recruitment until cleared.',
        date: '2026-07-10',
        read: false,
        severity: 'danger',
      },
      {
        id: 'notif-3',
        studentId: 'stu-1002',
        studentName: 'R. Vignesh',
        type: 'low_attendance',
        message: 'Attendance is 74.0% (Below mandatory 75% threshold). Risk of condonation fee.',
        date: '2026-07-12',
        read: false,
        severity: 'warning',
      },
    ],
  },
  {
    id: 'stu-1003',
    registerNo: '960721104003',
    name: 'S. Priyadharshini',
    email: 'priyadharshini.s@student.fxec.ac.in',
    phone: '+91 94422 33110',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    collegeId: 'col-1',
    collegeName: 'Francis Xavier Engineering College (Autonomous)',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    year: 4,
    semester: 7,
    section: 'A',
    cgpa: 8.82,
    gpaHistory: [
      { semester: 1, gpa: 8.60, cgpa: 8.60 },
      { semester: 2, gpa: 8.75, cgpa: 8.68 },
      { semester: 3, gpa: 8.90, cgpa: 8.75 },
      { semester: 4, gpa: 8.85, cgpa: 8.78 },
      { semester: 5, gpa: 8.95, cgpa: 8.81 },
      { semester: 6, gpa: 8.88, cgpa: 8.82 },
    ],
    arrearsHistory: [],
    pendingArrearsCount: 0,
    totalHistoryArrearsCount: 0,
    attendancePercentage: 94.2,
    collegeRank: 12,
    departmentRank: 3,
    classRank: 2,
    batchRank: 3,
    percentile: 97.5,
    placementStatus: 'eligible_placed',
    companyName: 'TCS Digital',
    packageCtc: '7.2 LPA',
    skills: ['Python', 'Data Analytics', 'Machine Learning', 'SQL', 'Tableau'],
    certifications: [
      'Microsoft Certified: Data Analyst Associate',
      'NPTEL Elite + Silver in Deep Learning',
    ],
    projects: [
      {
        title: 'Predictive Crop Yield Analytics for Southern TN Farmers',
        tech: 'Python, Scikit-learn, Flask',
        description: 'Machine learning model utilizing soil sensor data to forecast harvesting returns.',
      },
    ],
    hackathons: [
      { name: 'TCS CodeVita 2025', position: 'Global Top 500', year: '2025' },
    ],
    internships: [
      { company: 'TCS Innovation Lab, Chennai', role: 'Data Science Intern', duration: '3 Months' },
    ],
    interviewReadinessScore: 91,
    mentorId: 'men-101',
    mentorName: 'Dr. K. Arulraj',
    mentorRemarks: 'Very consistent performer. Active in department technical association events.',
    counselingNotes: [],
    notifications: [],
  },
  {
    id: 'stu-1004',
    registerNo: '960721104004',
    name: 'M. Mohamed Aslam',
    email: 'mohamedaslam.m@student.fxec.ac.in',
    phone: '+91 97890 12345',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200',
    collegeId: 'col-1',
    collegeName: 'Francis Xavier Engineering College (Autonomous)',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    year: 3,
    semester: 5,
    section: 'B',
    cgpa: 8.42,
    gpaHistory: [
      { semester: 1, gpa: 8.20, cgpa: 8.20 },
      { semester: 2, gpa: 8.40, cgpa: 8.30 },
      { semester: 3, gpa: 8.55, cgpa: 8.38 },
      { semester: 4, gpa: 8.50, cgpa: 8.42 },
    ],
    arrearsHistory: [],
    pendingArrearsCount: 0,
    totalHistoryArrearsCount: 0,
    attendancePercentage: 92.0,
    collegeRank: 48,
    departmentRank: 8,
    classRank: 4,
    batchRank: 8,
    percentile: 92.0,
    placementStatus: 'eligible_unplaced',
    skills: ['Flutter', 'Dart', 'Firebase', 'REST APIs', 'Git'],
    certifications: ['Google Flutter App Development Certification'],
    projects: [
      {
        title: 'FXEC Student Gate Pass & Hostel Automation App',
        tech: 'Flutter, Firebase',
        description: 'Mobile app used by 800+ hostel residents for digital Warden permission approvals.',
      },
    ],
    hackathons: [
      { name: 'HackFX 2025', position: 'Winner', year: '2025' },
    ],
    internships: [],
    interviewReadinessScore: 84,
    mentorId: 'men-101',
    mentorName: 'Dr. K. Arulraj',
    mentorRemarks: 'Strong mobile developer. Encouraged to take up competitive programming.',
    counselingNotes: [],
    notifications: [],
  },
  {
    id: 'stu-1005',
    registerNo: '960721205001',
    name: 'J. Abinaya',
    email: 'abinaya.j@student.fxec.ac.in',
    phone: '+91 93610 54321',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    collegeId: 'col-1',
    collegeName: 'Francis Xavier Engineering College (Autonomous)',
    departmentId: 'dept-it',
    departmentName: 'Information Technology',
    year: 4,
    semester: 7,
    section: 'A',
    cgpa: 8.65,
    gpaHistory: [
      { semester: 1, gpa: 8.50, cgpa: 8.50 },
      { semester: 2, gpa: 8.60, cgpa: 8.55 },
      { semester: 3, gpa: 8.70, cgpa: 8.60 },
      { semester: 4, gpa: 8.65, cgpa: 8.61 },
      { semester: 5, gpa: 8.72, cgpa: 8.63 },
      { semester: 6, gpa: 8.75, cgpa: 8.65 },
    ],
    arrearsHistory: [],
    pendingArrearsCount: 0,
    totalHistoryArrearsCount: 0,
    attendancePercentage: 95.0,
    collegeRank: 22,
    departmentRank: 2,
    classRank: 1,
    batchRank: 2,
    percentile: 95.8,
    placementStatus: 'eligible_placed',
    companyName: 'Infosys Power Programmer',
    packageCtc: '9.0 LPA',
    skills: ['Java', 'Spring Boot', 'Microservices', 'Docker', 'Kubernetes'],
    certifications: ['Infosys Certified Java Associate', 'NPTEL Cloud Computing'],
    projects: [
      {
        title: 'Microservices Based E-Commerce Backend',
        tech: 'Spring Boot, Docker, Redis',
        description: 'Scalable cloud infrastructure handling 5,000 requests/sec with JWT authentication.',
      },
    ],
    hackathons: [
      { name: 'Infosys HackWithInfy 2025', position: 'Top 100 Finalist', year: '2025' },
    ],
    internships: [
      { company: 'Infosys Mysore Campus', role: 'Systems Engineer Intern', duration: '4 Months' },
    ],
    interviewReadinessScore: 92,
    mentorId: 'men-102',
    mentorName: 'Prof. M. Lakshmi',
    mentorRemarks: 'Excellent analytical skills and code quality.',
    counselingNotes: [],
    notifications: [],
  },
  {
    id: 'stu-1006',
    registerNo: '960721114002',
    name: 'K. Balaji',
    email: 'balaji.k@student.fxec.ac.in',
    phone: '+91 95001 88990',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=200',
    collegeId: 'col-1',
    collegeName: 'Francis Xavier Engineering College (Autonomous)',
    departmentId: 'dept-mech',
    departmentName: 'Mechanical Engineering',
    year: 4,
    semester: 7,
    section: 'B',
    cgpa: 7.25,
    gpaHistory: [
      { semester: 1, gpa: 7.10, cgpa: 7.10 },
      { semester: 2, gpa: 7.00, cgpa: 7.05 },
      { semester: 3, gpa: 7.40, cgpa: 7.17 },
      { semester: 4, gpa: 7.30, cgpa: 7.20 },
      { semester: 5, gpa: 7.35, cgpa: 7.23 },
      { semester: 6, gpa: 7.30, cgpa: 7.25 },
    ],
    arrearsHistory: [
      {
        id: 'arr-20',
        subjectCode: 'ME3351',
        subjectName: 'Engineering Thermodynamics',
        semester: 3,
        status: 'passed_arrear',
        attemptCount: 2,
        clearingSemester: 4,
        grade: 'C',
      },
    ],
    pendingArrearsCount: 0,
    totalHistoryArrearsCount: 1,
    attendancePercentage: 86.5,
    collegeRank: 180,
    departmentRank: 15,
    classRank: 8,
    batchRank: 15,
    percentile: 72.0,
    placementStatus: 'eligible_placed',
    companyName: 'TVS Motors, Hosur',
    packageCtc: '4.8 LPA',
    skills: ['AutoCAD', 'SolidWorks', 'ANSYS', 'CNC Programming'],
    certifications: ['Certified SOLIDWORKS Associate (CSWA)'],
    projects: [
      {
        title: 'Design of Solar Powered EV Chassis',
        tech: 'SolidWorks, ANSYS Mechanical',
        description: 'Finite element structural stress simulation for lightweight electric 2-wheelers.',
      },
    ],
    hackathons: [],
    internships: [
      { company: 'TVS Motors Assembly Unit, Hosur', role: 'Production Line Intern', duration: '2 Months' },
    ],
    interviewReadinessScore: 78,
    mentorId: 'men-103',
    mentorName: 'Dr. S. Suresh',
    mentorRemarks: 'Cleared backlog in 4th sem. Good practical knowledge in CAD tools.',
    counselingNotes: [],
    notifications: [],
  },
  {
    id: 'stu-1007',
    registerNo: '960721302001',
    name: 'S. Nivedha',
    email: 'nivedha.s@student.fxec.ac.in',
    phone: '+91 96290 77665',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=200',
    collegeId: 'col-1',
    collegeName: 'Francis Xavier Engineering College (Autonomous)',
    departmentId: 'dept-aids',
    departmentName: 'Artificial Intelligence & Data Science',
    year: 3,
    semester: 5,
    section: 'A',
    cgpa: 9.42,
    gpaHistory: [
      { semester: 1, gpa: 9.30, cgpa: 9.30 },
      { semester: 2, gpa: 9.50, cgpa: 9.40 },
      { semester: 3, gpa: 9.45, cgpa: 9.42 },
      { semester: 4, gpa: 9.48, cgpa: 9.42 },
    ],
    arrearsHistory: [],
    pendingArrearsCount: 0,
    totalHistoryArrearsCount: 0,
    attendancePercentage: 98.2,
    collegeRank: 1,
    departmentRank: 1,
    classRank: 1,
    batchRank: 1,
    percentile: 99.9,
    placementStatus: 'eligible_unplaced',
    skills: ['PyTorch', 'TensorFlow', 'LLMs', 'Computer Vision', 'LangChain', 'Python'],
    certifications: [
      'DeepLearning.AI Generative AI Specialization',
      'NPTEL Topper (Top 1%) in Natural Language Processing',
    ],
    projects: [
      {
        title: 'Tamil Medical Prescription Handwriting OCR & Translation',
        tech: 'PyTorch, TrOCR, HuggingFace',
        description: 'AI model recognizing handwritten doctor prescriptions in rural health clinics.',
      },
    ],
    hackathons: [
      { name: 'Kaggle Global AI Challenge', position: 'Gold Medalist (Rank #8)', year: '2025' },
    ],
    internships: [
      { company: 'IIT Madras Research Park', role: 'AI Research Assistant', duration: '3 Months' },
    ],
    interviewReadinessScore: 98,
    mentorId: 'men-104',
    mentorName: 'Dr. R. Anitha',
    mentorRemarks: 'Department Rank 1. Outstanding researcher with 2 international paper publications.',
    counselingNotes: [],
    notifications: [],
  },
];

export const mockUserProfiles: Record<string, UserProfile> = {
  super_admin: {
    id: 'user-admin',
    name: 'Dr. V. Velmurugan',
    role: 'super_admin',
    email: 'principal@francisxavier.ac.in',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
  },
  hod_cse: {
    id: 'user-hod-cse',
    name: 'Dr. E. Manohar',
    role: 'hod',
    email: 'hod.cse@francisxavier.ac.in',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200',
  },
  mentor_arulraj: {
    id: 'user-mentor-arulraj',
    name: 'Dr. K. Arulraj',
    role: 'mentor',
    email: 'arulraj.k@francisxavier.ac.in',
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering',
    mentorId: 'men-101',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  },
};
